### ISSUE TITLE
Create Explore button

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#16]
### Description
We need to include the Explore button as an isolated component. This task could be helpful to get rid of unnecessary files created when Storybook was installed.

### Tasks
- [x] Remove template code created by Storybook installation.
- [x] Create the Explore button as an isolated component.
- [x] Add its story
- [x] Validate the behavior and its size in different viewports
- [x] Consider adding plugins to test Accessibility and/or Interaction
- [x] Include unit test with Testing Library
- [ ] Adjust Chromatic job to prevent build from failing
- [ ] Add job to check Storybook tests

### Notes
Continue checking [Storybook docs](https://storybook.js.org/docs/react/get-started/install)

#### Create a template for components
What if creating a whole new template for UI components could help to have a thorough checklist?

This could be useful to centralize the decision of creating different types of stories for different viewports or even, with different interactions. But also, taking care of edge cases such as: touch screen and user preferences (`prefers-reduced-motion`)

#### GitHub Actions
Seems like workflows only run with `npm`. Tried with `yarn` and the process failed without doing any operation. Further reading on [Stack Overflow thread](https://stackoverflow.com/questions/74176066/how-to-set-up-run-tests-at-ci-pipeline-with-storybook-and-github-actions)

**Comment by juanpb96** [comment]
Check [issue thread](https://github.com/storybookjs/test-runner/issues/301) to try a solution for CI validation
