### ISSUE TITLE
Create Navigation Bar

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#23]
### Description
We need to include the Navigation bar as an isolated component in Storybook. 

### Tasks
- [x] Add component file
- [x] Add Menu Button component
- [x] Include router component to validate Menu component behavior
- [x] Create stories for each viewport (mobile, tablet, and desktop)
- [x] Add display as hamburger menu on mobile
- [x] Handle styles for each state (active, hovered, and idle)
- [x] Include click interactions and tests
- [x] Validate keyboard navigation
- [x] Evaluate the need of keeping `@storybook/addon-styling`

### Notes
- Continue checking [Storybook docs](https://storybook.js.org/docs/react/get-started/install)
- Check [framer motion](https://www.framer.com/motion/introduction/##installation)

#### CSS Modules
While creating the hamburger button, styles from Explore button were present in the new one. A small [discovery ](https://stackoverflow.com/questions/65302337/css-file-is-applying-on-another-react-component-even-without-importing) explained that styles were being generated globally and to prevent this from happening was necessary to implement CSS Modules properly. Importing the file with a default name and accessing the desired class was the solution to this problem.

#### Changing args values / state in Storybook
Useful resources:
- [Named story exports - CSF](https://storybook.js.org/docs/react/api/csf#named-story-exports) - Using this information I was able to toggle the state of the button by implementing `render`. This was useful to understand how to create a story in which the component gets state props externally.
- [Changing args values / state in Storybook (without useState hook) + ReactJS](https://medium.com/urbandataanalytics/changing-args-values-state-in-storybook-without-usestate-hook-15cc096716f7) - This article explains how to add functionality into a component that depends on props. It highlights the importance of using `useArgs ` to keep the consistency between interaction with the component and the story's controls.

**Comment by juanpb96** [comment]
For reference: https://www.framer.com/motion/animate-function/

**Comment by juanpb96** [comment]
Inpiration: https://jonsuh.com/hamburgers/

**Comment by juanpb96** [comment]
Problem with Controls and state: https://github.com/storybookjs/storybook/issues/12006#issuecomment-1551404777

**Comment by juanpb96** [comment]
Prefers reduced motion: https://www.joshwcomeau.com/react/prefers-reduced-motion/

**Comment by juanpb96** [comment]
Accessibility guide for animations with Framer Motion: https://www.framer.com/motion/guide-accessibility/

**Comment by juanpb96** [comment]
Amazing explanation of Server-side vs Client-side and react routing: https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually/36623117#36623117

**Comment by juanpb96** [comment]
For reference: https://www.componentdriven.org/

**Comment by juanpb96** [comment]
It is important to use the `:hover` media query to target devices that support this feature and avoid relying only on the screen size
