### ISSUE TITLE
[Story] - Create Logo component

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#30]
### Description
It is necessary to include an isolated component that represents the logo of the project. 

### Tasks
- [x] Create a logo component
- [x] (Optional) Create a Visually Hidden component for the logo alt text
- [x] Logo component should have its own story
- [x] Logo image component must pass a11y checks

### Notes

We are not adding a hyperlink behavior in this component since the navbar is meant to appear across the site
