### ISSUE TITLE
[Story] - Create Header component

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#33]
### Description
Include a component that will be shown at the top of all the site pages. This component has to be composed of the logo and navigation bar. Also, a horizontal line must be between the logo and the navbar on large screens.

### Tasks
- [x] Create a header component
- [x] Add the `Logo` component
- [x] Add the `NavigationBar` component
- [x] Add a horizontal line for Desktop and larger screens
- [x] Create stories for the three viewport sizes (Storybook and Chromatic)
- [x] Validate passing a11y checks
