### ISSUE TITLE
[Story] - Create Subtitle component

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#35]
### Description
Create a Subtitle component that will be shared across different site pages. As this component shares almost all the styles, take special care of a variant that toggles the color and a main variant that includes a number as a prefix. 

### Tasks
- [x] Create a Subtitle component
- [x] Include styles for a variant with a number prefix
- [x] Include styles for a variant without prefix
- [x] Create a single story on Storybook
- [x] Validate component behavior on Storybook when props change
- [x] Test font changes on mobile, tablet, and desktop
- [x] Validate a11y checks passing

### Notes
The contrast check is failing because the prefix element has a low opacity. This cannot be fixed since it is part of the design spec.
