### ISSUE TITLE
[Story] - Create page main heading component

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#37]
### Description
It is necessary to add a component that can be used to attract user attention and let them know which is the specific topic the page talks about.

### Tasks
- [x] Create initial files
- [x] Apply base styles
- [x] This component should receive a prop that will be used to set the font-size
- [x] This component should have one story with controls to validate changes in font-size
- [x] Check variant behavior on mobile, tablet, and desktop
- [x] Validate a11y checks

### Notes
It should be a task to validate complete page semantics to discover if there is something to enhance.
