### ISSUE TITLE
[Story] - Create a paragraph component

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#39]
### Description
It is necessary to have a component that receives text and styles it according to the design spec. 

### Tasks
- [x] Create initial files
- [x] Apply base styles
- [x] This component should receive the text that needs to be styled
- [x] Create one story for Storybook
- [x] Check font-size changes on mobile, tablet, and desktop
- [x] Validate a11y checks

### Notes
I've been adding a calculation to obtain the expected line-height value. I consider it would be better to have a mixin or an independent sass function to get that value to stop repeating the same code multiple times in different components
