### ISSUE TITLE
[Spike] - Check how to use tags for project Releases

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#40]
### Description
It would be nice to have a better understanding of Releases in GitHub. This feature could come in handy in the future to improve project documentation by highlighting what is being introduced on each release.

### Tasks
- [ ] Investigate how Releases work in GitHub
- [ ] Check pros and cons
- [ ] Decide if using Releases could be beneficial in the current project
