### ISSUE TITLE
[Task] - Create README

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#42]
### Description
We need to update the readme.md file with all the details and insight gained during the development process.

### Tasks
- [x] Use the template provided by FEM
- [x] Include a link to the live site
- [x] Include a link to the public Storybook
- [ ] Check tickets created for ideas on continuous learning
- [ ] Update LinkedIn profile URL

### Notes
- To improve:
  - Understand how to create a relative path instead of having to import a file via its absolute path `../../../`
