### ISSUE TITLE
[Story] - Create the Home page

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#43]
### Description
In this story, we will start building the first page of the site. The home page should match the design and provide details regarding the creation of atomic components. 

### Tasks
- [x] Create Home page initial files
- [x] Create page structure based on available components
- [x] Create a story for each viewport to see how it behaves
- [x] When the user visits the "/" or "/home" route, the app should display the Home page component
- [x] Apply missing spacing above the `Header` 
- [x] Include background image
- [x] Gather information for possible improvements, fixes, and/or new features

### Notes
- Trying to implement the `NavigationBar`, to see how a page will look like, displayed a styles issue in which the menu is opened on mobile and the component looks kind of transparent. This looks odd and it is probably related to framer motion
  - This is not necessary to be addressed at the moment since it seems to be only showing on Storybook.
- `NavigationBar` applies the backdrop filter and the blur effect properly; however, some elements using Positioned Layout can appear one level above the menu when it is open
  - This will be tackled in [this issue](https://github.com/juanpb96/FEM_space-tourism-website/issues/44)
- In a future task, it is important to review Core Web Vitals on the deployed site to identify potential issues.
