### ISSUE TITLE
[Task] Remove branch after PR is merged

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#46]
### Description
Include in the merge-check job an action to delete the merged branch to reduce the branch clutter.

### Tasks
- [ ] Investigate how to delete the merged branch
- [ ] Include the action in the merge-check job
- [ ] Remove existing merged branches

### Notes
Once this passes the tests, remove existing merged branches
