### ISSUE TITLE
[Story] - Create Sub Navigation Bar

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#52]
### Description
Inside the Pick Your Destination page, there should be an additional navigation bar that will update the page content according to the selected planet by the user.  This bar should work independently from the main `NavigationBar` but the functionality (routing) will be added in another ticket.

### Tasks
- [x] Create initial files for the new navigation bar.
- [x] As this component will not change abruptly from mobile to desktop, it should have at least one story on Storybook.
- [x] Apply the same animation as in the `Menu` component
- [x] Include an interaction test
- [x] Check a11y
- [x] Validate font changes from mobile to desktop
