### ISSUE TITLE
[Story] - Create destination details

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#54]
### Description
It is necessary to create a component that will have a "title" and a "value" (See Avg. Distance or Est. Travel Time).

### Tasks
- [x] Create initial files
- [x] This component should show a title and a value
- [x] Add a Storybook story to represent its use
- [x] Check a11y
