### ISSUE TITLE
[Story] - Create Pick Your Destination page

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#56]
### Description
Create the page file and include components already created. In this first version, the page will only show static data; in the next task, a JSON file will be added to implement some "fake" API calls to dynamically show the content.

### Tasks
- [x] Create initial files
- [x] Create page structure
- [x] Add styles (background image, positioning)
- [x] Check on the actual route the layout behavior and take notes of possible adjustments
- [x] Create a Storybook story that will display this page per viewport (mobile, tablet, and desktop)
- [x] Check a11y

### Notes
- Routing and "API" calls will be tackled in the following task.
- It should be better to create breakpoints based on the data provided by [statcounter](https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide)
- Destination layout details in the actual route
  - The `Header` is growing infinitely and makes the design look weird on huge screens. Applying `max-width`  and increasing the `NavigationBar` background to occupy all the space on the right side could do the trick
  - Breakpoint should be fixed but for now, the code for this page can be merged and the layout must be adjusted in a different ticket once the breakpoints and components get enhanced accordingly
  - There are some Core Web Vitals checks that should be fixed in a future ticket but it is not urgent at this moment
