### ISSUE TITLE
[Story] - Routing and dynamically display data on Pick Your Destination page

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#58]
### Description
Include the route of the `Destination` page in the main `NavigationBar`, when the user clicks on it, the user should see the destination page. Additionally, the user should be able to toggle the page content by clicking on the options shown on the `InnerNavigationBar`. 

### Tasks
- [x] Clicking on the "Destination" option in the `NavigationBar` should navigate to the new `Destination` page
- [x] Add the `data.json` file in the project
- [x] Create an API call that should respond with the content for the planet or the moon requested by the user
- [x] Clicking on the `InnerNavigationBar` options should toggle the page content accordingly
- [x] Fix `InnerNavigationBar` bar width

### Notes
- It should be nice to validate how this change could affect the visualization of the page on Storybook
- Use case and API call implementation was inspired by [Nik Sumeiko](https://www.youtube.com/live/DQwNqSEvpk8?si=ZrzqzQL2EpENSXHQ&t=4064)
