### ISSUE TITLE
[Refactor] - Update project breakpoints

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#59]
### Description
Check [statcounter](https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide) and select proper breakpoints to enhance page usability. It is important to check all the components and adjust them if necessary.

### Tasks
- [x] Update application breakpoints
- [ ] Check components and pages, and adjust them if necessary
- [ ] Evaluate if the large-desktop viewport is needed or if it can be removed

### Notes
After manual testing using the regular font size, preferred viewport updates will be changed to 600px from mobile to tablet and 1300px from tablet to desktop.

#### Results of Manual Testing
- Home page
  - Tablet: Looks good if the transition happens at 600px
  - Desktop: Looks good set to 1300px
- Destination
  - Tablet: Looks good if the transition happens at 600px
    - [x] Adjust "Pick your destination" text to not have a negative margin until it is strictly required 
  - Desktop: Looks good set to 1300px
    - [x] Replace large desktop in media queries with desktop size  
- Crew
  - Tablet: Looks good if the transition happens at 600px
    - [x] Adjust "Meet your crew" text to not have a negative margin until it is strictly required 
  - Desktop: Looks good set to 1300px
    - [x] Replace large desktop in media queries with desktop size  
- Technology
  - Tablet: Looks good if the transition happens at 600px
  - Desktop: Looks good set to 1300px
    - [x] Portrait image should be shown in the new desktop size
    - [x] Content should be centered from the start of the desktop query
- 404 Error Page
  - Tablet: Looks good if the transition happens at 600px
  - Desktop: Looks good set to 1300px
