### ISSUE TITLE
[Task] - Handle routing from the backend server

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#64]
### Description
In this ticket, it is considered the implementation of routing from the backend to avoid the use of hash routing in the client.

### Tasks
- [ ] Investigate how to handle routes from the server
- [ ] Create a routing strategy in the backend server
- [ ] Update client side if necessary
- [ ] Test behavior

### Notes
- Current behavior:
    - When the user tries to enter `/destination` the user gets redirected to the homepage in local. In prod, the user will see a 404 error page.
- Expected behavior:
    - [ ] The user can visit a page directly without being redirected to the home page
    - [ ] The user can refresh the page and see the desired content not a 404 page 
- It will be necessary to think of an alternative on the client side in case the backend is not available for any reason
- https://stackoverflow.com/questions/36296012/is-there-a-configuration-in-github-pages-that-allows-you-to-redirect-everything
