### ISSUE TITLE
[Task] - Optimizing Data Fetching and Request Handling

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#65]
### Description
It's essential to optimize the number of calls made when fetching data for each page. Currently, it appears that a request is sent each time a user accesses a page. This practice can be inefficient, especially when users repeatedly visit the same page within a session and only perform GET requests. It would be more efficient to preload the data so that it's readily available during subsequent visits within the same session, reducing unnecessary server calls.

### Tasks
- [x] Check and document findings regarding fetch requests across the site
- [x] If the assumption is correct, look for the best way to optimize data fetching
- [x] It'd be an option to fall back to the local data if the server response takes too long and keep the response in the background (use cache?).
- [x] Are images being cached or are they always received from the server?

### Notes
- Navigating for the first time to "Destinations" could cause a delay of more than 45 seconds to receive data
- To display data fast to the user, consider the implementation of the local JSON file first
    - Doing this will help reduce the time to paint key content
    - A request will be sent in the background to ensure data can be retrieved from the backend
    - Showing a "badge" mentioning the use of fallback data (JSON file)  could enhance user experience. This badge must be removed if data from the server has been retrieved properly and page content has been updated

**Comment by juanpb96** [comment]
Performance analysis cannot be executed due to client routing. It'd be better to do these tests once the [Issue 64](https://github.com/juanpb96/FEM_space-tourism-website/issues/64) is resolved.

**Comment by juanpb96** [comment]
Further reading to learn more about how to test when there are API calls
https://kentcdodds.com/blog/stop-mocking-fetch

**Comment by juanpb96** [comment]
Displaying data from the local JSON file can be used as a fallback until the backed data has been retrieved properly, this will help to reduce waiting time.  Updating the localStorage could be the option to validate if the backend data becomes available.
