### ISSUE TITLE
[Story] - Create Pagination component for Crew page

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#70]
### Description
In this task, the component for the carousel pagination should be created and focused on UI only, functionality will be added later.

### Tasks
- [x] Create initial files
- [x] Create a component story in Storybook
- [x] It should handle active state
- [x] It should handle inactive state
- [x] It should handle the hover state

### Notes
- Focus state should be added when interaction is implemented.
