### ISSUE TITLE
[Story] - Build Meet Your Crew page UI

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#72]
### Description
In this task, the Meet Your Crew page needs to be built. This will be the first step before adding the entire information to support the slider and every crew member.

### Tasks
- [x] Create page file
- [x] Create Storybook story for this page
- [x] Build page with existing UI components
- [x] The initial data displayed should be of the crew member "Douglas Hurley"
