### ISSUE TITLE
[Story] - Create Technology page

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#76]
### Description
In this task, the Technology page will be created. This task will solely be focused on UI.

### Tasks
- [x] Create page file
- [x] Create a Storybook story for this page per viewport
- [x] Create Pagination component
- [x] Build the page with existing UI components
- [x] Create the pagination component used in this page
- [x] The initial data displayed should be of the "LAUNCH VEHICLE"

**Comment by juanpb96** [comment]
**Continuos development:** It would be more legible if instead of using absolute paths the relative paths were implemented to have a clear import definition in the files
