### ISSUE TITLE
[Story] - Crew Page - Display crew data dinamically

### ISSUE THREAD

**Issue by juanpb96** [juanpb96/FEM_space-tourism-website#79]
### Description
This story tackles the functionality of the Crew page in which the user clicks a "dot" to see other crew members' information.

### Tasks
- [x] Toggle crew member information (name, description, and image) when the user clicks a "dot".
- [ ] Update layout and styles to enhance the user experience when toggling crew members.
- [x] Check the complexity of adding a carousel functionality.

### Notes
- When the user toggles crew member (Leaving this task for future implementation as it is not crucial for the first version)
    - [ ] Text structure for every crew member should be kept in the same place
- Adding some enter and exit animations or transitions instead of a whole carousel could be better. However, this can be tackled in a future increment. 
    - [x] Create an issue to keep track of this in a new milestone [Issue #80](https://github.com/juanpb96/FEM_space-tourism-website/issues/80)
- There is a lack of space in the description of the crew member Victor Glover
    - [x] Create an issue to keep track of BE minor fixes [Issue #81](https://github.com/juanpb96/FEM_space-tourism-website/issues/81)
